### ISSUE TITLE
Schedule App Content Meta-Ticket

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/mozillafestival.org#1069]
For the Mozilla Festival 2018 guide on Guidebook, we've started this year's content by copying over data from the 2017 guide. 

Various updates are needed on the guide for 2018. This ticket will house all major and minor changes, major changes will have their own ticket.

If anyone has feedback about content from last year's guide please feel free to comment on this thread.

---

### General Info
- [x] Short descirption required for an overview of MozFest 2018
- [x] Decide on 'Location' marked in app (there can only be one).

### Schedule
- [x] (Tracks) Updates to Space names and new descirptions.
- [ ] (Tracks) Update descirption for D&D space.
- [x] (Tracks) Add new Experiences with descirptions

### Maps / Locations
- [ ] Update maps with 2018 designs and labels.

### Safety & Emergency 
- [x] Update new condensed version of 'Participation Guidelines'
- [x] Update 'Raising Issues at MozFest' based on (#977)
- [ ] Confirm workflow for Flagging Inapporiate Content on Guidebook

### Ticketing
- [x] Decide if this is /tickets or the ti.to timeline of all Festival events.

### Watch Live
- [x] AirMo or YouTube?

### MozFest House
- [x] Make MFH more prominent in Guidebook this year
- [x] Descirption for MozFest House (#960)

### Sponsors
- [x] Do we include sponsors on their own tab this year?

### New Pages
- [x] Wranglers
- [ ] Feedback Form
- [ ] Frequently Asked Questions

**Comment by marcwalsh** [comment]
Looping in @Saallen @consuelamckenzie @zee-moz @mmmavis 

Feel free to jump in - the majority of this content will hopefully be dervied from the Printed Festival Guide Content (#1031)

**Comment by marcwalsh** [comment]
After speaking with @consuelamckenzie we're also looking to add these additional pages:

- Wranglers
- FAQs
- Feedback Form

I'll update the ticket above with these new tasks.

**Comment by gideonthomas** [comment]
@marcwalsh would you be able to update this with content? Festival guide content is ready here: https://docs.google.com/document/d/1E7hHGmiqRS9ggZR71TQPNEpdY0BlNfi7IiaQTyO4Abk/edit#

**Comment by gideonthomas** [comment]
@marcwalsh what is the status of this ticket?

**Comment by gideonthomas** [comment]
Adding this here as well (from #1068) in case it's needed:

Location Info:

**Spaces**
* Youth zone - 2
* Web Literacy - Library
* Decentralisation - level 6
* Openness- 7
* Digital Inclusion - level 8
* Privacy and Security - level 9

**Experiences**
Art+Data - M (or mezzanine) 
Tracked - 5
Queering MozFest - 6

**Extra areas**- (that dont have to be on the map but might have high footfall)
Mozilla Zone - 1 
Emergent Sessions  - 8
Prototyping Lab 9


Other content:

    Registration- 0
    Dialogues & Debates Stage - 0
    Main Stage - 4
    #MozHelp - 4
    Quiet Space - 0
    Lunch- 0, 4, 7, 9
    Info Booth - at entrance to 2, 6, 7, 8, 9
    Coffee 0, 5, 9 
    Water- all floors (same as last year)
    Toilets all floors ( same as last year)
(Private access internet) Lounge 5
