### ISSUE TITLE
Festival Guide content meta-ticket

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#691]
This is a meta-ticket for wrangling all the MozFest Festival Guide content.
See 2016 [Festival Guide](https://issuu.com/mozfest/docs/mozfest-2016) as reference

- [x] Front cover #692 
- [x] Welcome message #693
- [x] Schedule overview #694
- [x] Spaces #695
- [x] Theme Curation #725 (may be possible to combine with Spaces or Artists Open Studios under an Experiences heading)
- [x] Artists Open Studios #724
- [x] Speakers #696
- [x] How to MozFest #697
- [x] Accessible MozFest #698
- [x] Network for Internet Health #699
- [x] Working open #700
- [x] MozFest House #701
- [x] Sponsors #702
- [x] Participation Guidelines on back cover #703
- [x] Wrangler bios #743
- [x] ~~[backup page] About Mozilla #721~~

**Comment by cassiemc** [comment]
Wow, look at all those check marks. Almost there, go @edrushka go! :1st_place_medal: 

FYI I'm collecting all content here for design: https://docs.google.com/a/mozilla.com/document/d/1fzQxF_l3oiy-U-GLQXIB78Y5dDGX_5SWtQvrAZBHm3E/edit?usp=sharing It's okay if it changes I just wanted to get a sense of how much content there was in one place, how long, and start paginating. We can put in final final content later.

What is the best source for 2016 Mozfest photos?

**Comment by edrushka** [comment]
Best source is: https://www.flickr.com/photos/mozfest/albums

**Comment by edrushka** [comment]
@cassiemc I've added the Wrangler Bios #743 to the table of contents, since they might be included in the main guide. I'm waiting for one final photo and a final entry for the youth zone. I'll let you know when I've added them in.

**Comment by cassiemc** [comment]
All of these are closed now expect Sponsors #702

**Comment by edrushka** [comment]
Guide is finished and printed. It looks stunning! 💟
