### ISSUE TITLE
Tidy up codebase

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#800]
- [x] upgrade outdated dependencies
- [ ] ES6-fy things (most likely won't fully finish this by this sprint... since there are a ton of code to turn into ES6)
- [ ] make sure we have GA set up and user's DNT preference is respected
- [x] enable "real" server side rendering (currently the server serves index.html and let bundle.js and client side `react-router` handle the rest)
- [x] 404 page (with http status 404)
- [x] make sure og tags / `react-helmet` is properly set up
- [x] upgrade `react-router` to v4.2.0

My plan is to tidy up the codebase a bit before asking someone to review this currently-in-chaos codebase.

**Comment by mmmavis** [comment]
Closing this Epic ticket.

> ES6-fy things (most likely won't fully finish this by this sprint... since there are a ton of code to turn into ES6)

This is ongoing work.

>  make sure we have GA set up and user's DNT preference is respected

This is blocked - I'm unable to get access to the GA Dashboard so I can't test.
