### ISSUE TITLE
Program (Curation) Repository

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#855]
Working open is one of our core values, MozFest program planning is done in the open on Github.

- [x] https://github.com/mozilla/mozillafestival.org/issues/878 Set up 2018 repo
- [x] https://github.com/mozilla/mozillafestival.org/issues/877 Write readme for 2018 repo
- [ ] Decide labels, milestones, issue format and how we display metadata

**Comment by sabrinang** [comment]
@Saallen to decide labels, milestones, issue format and how we display metadata to help organize proposals and content in the repo

**Comment by mmmavis** [comment]
I created a GitHub Org "MozillaFestival" for us! 2018 program repo is now there under this org instead: https://github.com/MozillaFestival/mozfest-program-2018

I will update this ticket with the proposed labels/milestone we want to use and we can revise from there.

**Comment by mmmavis** [comment]
## Milestone

(a proposal's primary space choice) (a ticket can only have max of 1 milestone applied)

1. `Decentralization`
2. `Digital Inclusion`
3. `Openness`
4. `Privacy and Security`
5. `Web Literacy`
6. `Youth Zone`
7. `Queering MozFest`

## Labels

(a ticket can have multiple labels)

### Session Format

1. `[Format] Learning Forum`
2. `[Format] Shed`
3. `[Format] Gallery`

### Secondary Space

1. `[Secondary Space] Decentralization`
2. `[Secondary Space] Digital Inclusion`
3. `[Secondary Space] Openness`
4. `[Secondary Space] Privacy and Security`
5. `[Secondary Space] Web Literacy`
6. `[Secondary Space] Youth Zone`

### Localisation related

1. `Localisation support requested`
2. `[LANG] Spanish`
3. `[LANG] French`
4. `[LANG] Italian`
5. `[LANG] Hindi`
6. `[LANG] Bengali`
7. `[LANG] German`
8. `[LANG] Russian`
9. `[LANG] Greek`
10. `[LANG] Portugese`
11. `[LANG] Mandarin`
12. `[LANG] Other`

### Stipend related

1. `Stipend requested`

**Comment by mmmavis** [comment]
# GitHub ticket template (see sample below)

**[ UUID ]** cf0f44a5-8190-4d29-87e8-fe960c038dba

**[ Session Name ]** im the session name
**[ Primary Space ]** Queering MozFest
**[ Secondary Space ]** Privacy and Security

**[ Submitter's Name ]** myfirstnameee mysurnameee
**[ Submitter's Affiliated Organisation ]** organisationnn
**[ Submitter's GitHub ]** @githubhandlehahahah

**[ Other Facilitator 1's Name ]** firstname1 surname1
**[ Other Facilitator 1's GitHub ]** @otherfacilitator1_githubhandle

**[ Other Facilitator 2's Name ]** firstname2 surname2
**[ Other Facilitator 2's GitHub ]** @otherfacilitator2_githubhandle

**[ Other Facilitator 3's Name ]** firstname3 surname3
**[ Other Facilitator 3's GitHub ]** @otherfacilitator3_githubhandle


---

**[ Language ]** Portugese
**[ Localisation Support Requested ]** No, I can host the sessions myself

---


### What will happen in your session?
descriptionnnn
line2
line3

### What is the goal or outcome of your session?
outcomeeee
line2
line3


### If your session requires additional materials or electronic equipment, please outline your needs.
needsss
line2
line3
line4


### Time needed
60 mins

**Comment by mmmavis** [comment]
# Teams have been created on the program repo (we can add more)

![screen shot 2018-05-25 at 6 00 01 pm](https://user-images.githubusercontent.com/2896608/40570968-8aa7e13e-6045-11e8-924c-1163bc1a0fdf.png)

**Comment by mmmavis** [comment]
DONE!

🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉
