### ISSUE TITLE
Team page: Update bios and photos

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#934]
https://mozillafestival.org/team

Update the production tab to include:
- [x] #940 Update Tom Farrow 
- [x] #937 Update Robert Sayles
- [x] #938 Update Production Coordinator
- [x] #991 Update Production Manager
- [x] #936 Update Gunner
- [x] #935 Update Mark Surman

Update the wranglers page to include:
- [x] exported wrangler's photo from https://github.com/mozilla/mozillafestival.org/issues/933
- [x] reviewed wrangler's bio + twitter handle from https://github.com/mozilla/mozillafestival.org/issues/852
- [x] other bio related changes (refer to issue https://github.com/mozilla/mozillafestival.org/issues/922 )

**Comment by sabrinang** [comment]
@mmmavis https://github.com/mozilla/mozillafestival.org/issues/933#issuecomment-401191993 photos have been exported

**Comment by Saallen** [comment]
Production assistant and coordinator are not in place yet so @mmmavis update other bios this heart beat and we will do PA and PC LATER

**Comment by mmmavis** [comment]
@sabrinang should we close this ticket? We can use #939 to track Production Assistant bio once that person is hired.

**Comment by sabrinang** [comment]
@mmmavis Yes, since the production assistant is not hired let's not let it block this ticket and track on #939 independently 👍
